// backend/config/paperPattern.config.js
module.exports = {
  class10: {
    totalMarks: 80,
    totalQuestions: 38,
    timeAllowed: "3 Hours",
    generalInstructions: [
      "This question paper contains 38 questions. All questions are compulsory.",
      "Question paper is divided into FIVE sections - Section A, B, C, D and E.",
      "In Section A, Questions no. 1 to 18 are multiple choice questions (MCQs) and questions no. 19 and 20 are Assertion-Reason based questions of 1 mark each.",
      "In Section B, Questions no. 21 to 25 are very short answer (VSA) type questions of 2 marks each.",
      "In Section C, Questions no. 26 to 31 are short answer (SA) type questions of 3 marks each.",
      "In Section D, Questions no. 32 to 35 are long answer (LA) type questions of 5 marks each.",
      "In Section E, Questions no. 36 to 38 are case study based questions of 4 marks each.",
      "Internal choice is provided in 2 marks, 3 marks, 5 marks and case study questions.",
      "There is no overall choice. However, internal choice has been provided.",
    ],
    sections: [
      {
        section: "A",
        type: "Multiple Choice Questions",
        marks: 1,
        count: 20,
        subtype: "MCQ",
      },
      {
        section: "B",
        type: "Very Short Answer Questions",
        marks: 2,
        count: 5,
        subtype: "VSA",
      },
      {
        section: "C",
        type: "Short Answer Questions",
        marks: 3,
        count: 6,
        subtype: "SA",
      },
      {
        section: "D",
        type: "Long Answer Questions",
        marks: 5,
        count: 4,
        subtype: "LA",
      },
      {
        section: "E",
        type: "Case Study Based Questions",
        marks: 4,
        count: 3,
        subtype: "Case Study",
      },
    ],
  },

  class12: {
    totalMarks: 70,
    totalQuestions: 33,
    timeAllowed: "3 Hours",
    generalInstructions: [
      "This question paper contains 33 questions. All questions are compulsory.",
      "Question paper is divided into FIVE sections - Section A, B, C, D and E.",
      "Section A consists of 16 multiple choice questions of 1 mark each.",
      "Section B consists of 5 very short answer questions of 2 marks each.",
      "Section C consists of 7 short answer questions of 3 marks each.",
      "Section D consists of 2 case study based questions of 4 marks each.",
      "Section E consists of 3 long answer questions of 5 marks each.",
      "Internal choice is available in some sections.",
      "Use of calculators is not permitted.",
    ],
    sections: [
      {
        section: "A",
        type: "Multiple Choice Questions",
        marks: 1,
        count: 16,
        subtype: "MCQ",
      },
      {
        section: "B",
        type: "Very Short Answer Questions",
        marks: 2,
        count: 5,
        subtype: "VSA",
      },
      {
        section: "C",
        type: "Short Answer Questions",
        marks: 3,
        count: 7,
        subtype: "SA",
      },
      {
        section: "D",
        type: "Case Study Based Questions",
        marks: 4,
        count: 2,
        subtype: "Case Study",
      },
      {
        section: "E",
        type: "Long Answer Questions",
        marks: 5,
        count: 3,
        subtype: "LA",
      },
    ],
  },
};
